version: "3.0"
services:
  budgeteer:
    image: budgeteerorg/budgeteer
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
    - "./config/:/config/:ro"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=budgeteer
      - POSTGRES_PASSWORD=budgeteer
      - POSTGRES_DB=budgeteer
    ports:
      - "5432:5432"
    volumes:
    - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
