--------------------------------------------------------
--  Datei erstellt -Mittwoch-Dezember-19-2018
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 72 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BUDGET_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_BUDGET_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRACT_FIELD_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_CONTRACT_FIELD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRACT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_CONTRACT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRACT_INVOICE_FIELD_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_CONTRACT_INVOICE_FIELD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICE_FIELD_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_INVOICE_FIELD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_INVOICE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROJECT_CONTRACT_FIELD_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUDGETEER"."SEQ_PROJECT_CONTRACT_FIELD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BUDGET
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."BUDGET"
   (	"ID" NUMBER(19,0),
	"DESCRIPTION" VARCHAR2(255 CHAR),
	"IMPORT_KEY" VARCHAR2(255 CHAR),
	"LIMIT" NUMBER(19,0),
	"NAME" VARCHAR2(255 CHAR),
	"NOTE" CLOB,
	"TOTAL" NUMBER(19,0),
	"CONTRACT_ID" NUMBER(19,0),
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("NOTE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BUDGETEER_USER
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."BUDGETEER_USER"
   (	"ID" NUMBER(19,0),
	"MAIL" VARCHAR2(255 CHAR),
	"MAIL_VERIFIED" NUMBER(1,0),
	"NAME" VARCHAR2(255 CHAR),
	"PASSWORD" VARCHAR2(512 CHAR),
	"DEFAULT_PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUDGET_TAG
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."BUDGET_TAG"
   (	"ID" NUMBER(19,0),
	"TAG" VARCHAR2(255 CHAR),
	"BUDGET_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTRACT
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."CONTRACT"
   (	"ID" NUMBER(19,0),
	"BUDGET" NUMBER(19,0),
	"CONTRACT_FILE" BLOB,
	"FILE_NAME" VARCHAR2(255 CHAR),
	"INTERNAL_NUMBER" VARCHAR2(255 CHAR),
	"LINK" VARCHAR2(255 CHAR),
	"CONTRACT_NAME" VARCHAR2(255 CHAR),
	"START_DATE" DATE,
	"TAXRATE" NUMBER(10,4),
	"CONTRACT_TYPE" NUMBER(10,0),
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("CONTRACT_FILE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONTRACT_FIELD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."CONTRACT_FIELD"
   (	"ID" NUMBER(19,0),
	"CONTRACT_FIELD_VALUE" VARCHAR2(255 CHAR),
	"CONTRACT_ID" NUMBER(19,0),
	"PROJECT_CONTRACT_FIELD" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTRACT_INVOICE_FIELD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD"
   (	"ID" NUMBER(19,0),
	"FIELD_NAME" VARCHAR2(255 CHAR),
	"CONTRACT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAILY_RATE
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."DAILY_RATE"
   (	"ID" NUMBER(19,0),
	"DATE_END" DATE,
	"DATE_START" DATE,
	"RATE" NUMBER(19,0),
	"BUDGET_ID" NUMBER(19,0),
	"PERSON_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORGOT_PASSWORD_TOKEN
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."FORGOT_PASSWORD_TOKEN"
   (	"ID" NUMBER(19,0),
	"EXPIRY_DATE" TIMESTAMP (6),
	"TOKEN" VARCHAR2(255 CHAR),
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMPORT
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."IMPORT"
   (	"ID" NUMBER(19,0),
	"END_DATE" TIMESTAMP (6),
	"IMPORT_DATE" TIMESTAMP (6),
	"IMPORT_TYPE" VARCHAR2(255 CHAR),
	"NUMBER_OF_IMPORTED_FILES" NUMBER(10,0),
	"START_DATE" TIMESTAMP (6),
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."INVOICE"
   (	"ID" NUMBER(19,0),
	"SENT_DATE" DATE,
	"DUE_DATE" DATE,
	"INVOICE_FILE" BLOB,
	"FILE_NAME" VARCHAR2(255 CHAR),
	"INTERNAL_NUMBER" VARCHAR2(255 CHAR),
	"INVOICE_SUM" NUMBER(19,0),
	"URL" VARCHAR2(255 CHAR),
	"MONTH" NUMBER(10,0),
	"NAME" VARCHAR2(255 CHAR),
	"PAID_DATE" DATE,
	"YEAR" NUMBER(10,0),
	"CONTRACT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("INVOICE_FILE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table INVOICE_FIELD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."INVOICE_FIELD"
   (	"ID" NUMBER(19,0),
	"INVOICE_FIELD_VALUE" VARCHAR2(255 CHAR),
	"CONTRACT_INVOICE_FIELD_ID" NUMBER(19,0),
	"INVOICE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."PERSON"
   (	"ID" NUMBER(19,0),
	"IMPORT_KEY" VARCHAR2(255 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAN_RECORD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."PLAN_RECORD"
   (	"ID" NUMBER(19,0),
	"DAILY_RATE" NUMBER(19,0),
	"RECORD_DATE" DATE,
	"RECORD_DAY" NUMBER(10,0),
	"MINUTES" NUMBER(10,0),
	"RECORD_MONTH" NUMBER(10,0),
	"RECORD_WEEK" NUMBER(10,0),
	"RECORD_YEAR" NUMBER(10,0),
	"BUDGET_ID" NUMBER(19,0),
	"IMPORT_ID" NUMBER(19,0),
	"PERSON_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."PROJECT"
   (	"ID" NUMBER(19,0),
	"NAME" VARCHAR2(255 CHAR),
	"PROJECT_END" DATE,
	"PROJECT_START" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_CONTRACT_FIELD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD"
   (	"ID" NUMBER(19,0),
	"FIELD_NAME" VARCHAR2(255 CHAR),
	"PROJECT_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_USER
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."PROJECT_USER"
   (	"PROJECT_ID" NUMBER(19,0),
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEMPLATE
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."TEMPLATE"
   (	"ID" NUMBER(19,0),
	"DESCRIPTION" VARCHAR2(512 CHAR),
	"ISDEFAULT" NUMBER(1,0),
	"NAME" VARCHAR2(128 CHAR),
	"PROJECT_ID" NUMBER(19,0),
	"TYPE" NUMBER(10,0),
	"TEMPLATE" BLOB
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("TEMPLATE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table VERIFICATION_TOKEN
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."VERIFICATION_TOKEN"
   (	"ID" NUMBER(19,0),
	"EXPIRY_DATE" TIMESTAMP (6),
	"TOKEN" VARCHAR2(255 CHAR),
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK_RECORD
--------------------------------------------------------

  CREATE TABLE "BUDGETEER"."WORK_RECORD"
   (	"ID" NUMBER(19,0),
	"DAILY_RATE" NUMBER(19,0),
	"RECORD_DATE" DATE,
	"RECORD_DAY" NUMBER(10,0),
	"MINUTES" NUMBER(10,0),
	"RECORD_MONTH" NUMBER(10,0),
	"RECORD_WEEK" NUMBER(10,0),
	"RECORD_YEAR" NUMBER(10,0),
	"EDITED_MANUALLY" NUMBER(1,0),
	"BUDGET_ID" NUMBER(19,0),
	"IMPORT_ID" NUMBER(19,0),
	"PERSON_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_IMPORT_KEY_PER_PROJECT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UNIQUE_IMPORT_KEY_PER_PROJECT" ON "BUDGETEER"."BUDGET" ("PROJECT_ID", "IMPORT_KEY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UNIQUE_USER_NAME" ON "BUDGETEER"."BUDGETEER_USER" ("NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMPORT_PROJECT_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."IMPORT_PROJECT_ID_IDX" ON "BUDGETEER"."IMPORT" ("PROJECT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BUDGET_TAG_BUDGET_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."BUDGET_TAG_BUDGET_ID_IDX" ON "BUDGETEER"."BUDGET_TAG" ("BUDGET_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSON_PROJECT_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."PERSON_PROJECT_ID_IDX" ON "BUDGETEER"."PERSON" ("PROJECT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK946XLP22T9RMFVA05WL0T1Y5O
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UK946XLP22T9RMFVA05WL0T1Y5O" ON "BUDGETEER"."PROJECT_CONTRACT_FIELD" ("FIELD_NAME", "PROJECT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_PROJECT_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UNIQUE_PROJECT_NAME" ON "BUDGETEER"."PROJECT" ("NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_FIELD_NAME_PER_CONTRACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UNIQUE_FIELD_NAME_PER_CONTRACT" ON "BUDGETEER"."CONTRACT_INVOICE_FIELD" ("FIELD_NAME", "CONTRACT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAN_RECORD_BUDGET_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."PLAN_RECORD_BUDGET_ID_IDX" ON "BUDGETEER"."PLAN_RECORD" ("BUDGET_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORK_RECORD_BUDGET_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."WORK_RECORD_BUDGET_ID_IDX" ON "BUDGETEER"."WORK_RECORD" ("BUDGET_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER_MAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUDGETEER"."UNIQUE_USER_MAIL" ON "BUDGETEER"."BUDGETEER_USER" ("MAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORK_RECORD_PERSON_ID_IDX
--------------------------------------------------------

  CREATE INDEX "BUDGETEER"."WORK_RECORD_PERSON_ID_IDX" ON "BUDGETEER"."WORK_RECORD" ("PERSON_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUDGET_TAG
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGET_TAG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGET_TAG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORGOT_PASSWORD_TOKEN
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."FORGOT_PASSWORD_TOKEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."FORGOT_PASSWORD_TOKEN" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."FORGOT_PASSWORD_TOKEN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_RECORD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("DAILY_RATE" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("RECORD_DAY" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("MINUTES" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("RECORD_MONTH" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("RECORD_WEEK" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("RECORD_YEAR" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("BUDGET_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("IMPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."WORK_RECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PERSON" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PERSON" MODIFY ("IMPORT_KEY" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PERSON" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PERSON" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PERSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DAILY_RATE
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."DAILY_RATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."DAILY_RATE" MODIFY ("BUDGET_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."DAILY_RATE" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."DAILY_RATE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMPLATE
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."TEMPLATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."TEMPLATE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT_USER
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PROJECT_USER" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUDGET
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGET" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGET" MODIFY ("IMPORT_KEY" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGET" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGET" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGET" ADD CONSTRAINT "UNIQUE_IMPORT_KEY_PER_PROJECT" UNIQUE ("PROJECT_ID", "IMPORT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."BUDGET" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUDGETEER_USER
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" ADD CONSTRAINT "UNIQUE_USER_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" ADD CONSTRAINT "UNIQUE_USER_MAIL" UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VERIFICATION_TOKEN
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."VERIFICATION_TOKEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."VERIFICATION_TOKEN" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."VERIFICATION_TOKEN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRACT_INVOICE_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" MODIFY ("FIELD_NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" ADD CONSTRAINT "UNIQUE_FIELD_NAME_PER_CONTRACT" UNIQUE ("FIELD_NAME", "CONTRACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLAN_RECORD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("DAILY_RATE" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("RECORD_DAY" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("MINUTES" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("RECORD_MONTH" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("RECORD_WEEK" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("RECORD_YEAR" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("BUDGET_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("IMPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMPORT
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."IMPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."IMPORT" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."IMPORT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRACT_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT_FIELD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT_FIELD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."INVOICE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."INVOICE" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."INVOICE" ADD CHECK (month>=0 AND month<=11) ENABLE;
  ALTER TABLE "BUDGETEER"."INVOICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT" MODIFY ("CONTRACT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."CONTRACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT_CONTRACT_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" MODIFY ("FIELD_NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" ADD CONSTRAINT "UK946XLP22T9RMFVA05WL0T1Y5O" UNIQUE ("FIELD_NAME", "PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."INVOICE_FIELD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."INVOICE_FIELD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PROJECT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BUDGETEER"."PROJECT" ADD CONSTRAINT "UNIQUE_PROJECT_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUDGETEER"."PROJECT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUDGET
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGET" ADD CONSTRAINT "FKBK1WKBD75K2SBHHX24EYDPER7" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."BUDGET" ADD CONSTRAINT "FKEVT0TUBXK34Q8QT4X2EKF3U0F" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "BUDGETEER"."CONTRACT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUDGETEER_USER
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGETEER_USER" ADD CONSTRAINT "FKGTRMVTGXM03Q0FET9LAK8R7FR" FOREIGN KEY ("DEFAULT_PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUDGET_TAG
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."BUDGET_TAG" ADD CONSTRAINT "FKSAHMDVRBHTGG775DJ4HVLMADD" FOREIGN KEY ("BUDGET_ID")
	  REFERENCES "BUDGETEER"."BUDGET" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT" ADD CONSTRAINT "FKIUHNXIUG4XIXTCQ9H6GTYCXXH" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRACT_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT_FIELD" ADD CONSTRAINT "FK9OR9NQTMNWJHKC1QXOJ8EX2KS" FOREIGN KEY ("PROJECT_CONTRACT_FIELD")
	  REFERENCES "BUDGETEER"."PROJECT_CONTRACT_FIELD" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."CONTRACT_FIELD" ADD CONSTRAINT "FKD8UP5AGIESB1KJEYYLQ5CCRJK" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "BUDGETEER"."CONTRACT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRACT_INVOICE_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."CONTRACT_INVOICE_FIELD" ADD CONSTRAINT "FKCIAEVR8YSU0JAMH258CI14JHE" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "BUDGETEER"."CONTRACT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DAILY_RATE
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."DAILY_RATE" ADD CONSTRAINT "FK6PX4J6Y8KDWWH48R927YYMMOK" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "BUDGETEER"."PERSON" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."DAILY_RATE" ADD CONSTRAINT "FKMK4O49JG5GYLAT1V55Y3GR7DN" FOREIGN KEY ("BUDGET_ID")
	  REFERENCES "BUDGETEER"."BUDGET" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORGOT_PASSWORD_TOKEN
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."FORGOT_PASSWORD_TOKEN" ADD CONSTRAINT "FKFNIW3PQ63SI1QKSW95D2SGMT9" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUDGETEER"."BUDGETEER_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMPORT
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."IMPORT" ADD CONSTRAINT "FK1EGSPEAWIJ8O52CKN75N0DI8U" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."INVOICE" ADD CONSTRAINT "FKQH9IBAACFUSHT7AN2AFWKRQ5" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "BUDGETEER"."CONTRACT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."INVOICE_FIELD" ADD CONSTRAINT "FK747F8GKCYU46LCQEINJVPW5F1" FOREIGN KEY ("CONTRACT_INVOICE_FIELD_ID")
	  REFERENCES "BUDGETEER"."CONTRACT_INVOICE_FIELD" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."INVOICE_FIELD" ADD CONSTRAINT "FKG5HQBTIKNGQRK4R29CYWL50U0" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "BUDGETEER"."INVOICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PERSON" ADD CONSTRAINT "FKE70AP0SUQKP9R991MKH9H1V1V" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAN_RECORD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PLAN_RECORD" ADD CONSTRAINT "FK3L6QR6Y4TGB5KHIGMAT55ORGQ" FOREIGN KEY ("BUDGET_ID")
	  REFERENCES "BUDGETEER"."BUDGET" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" ADD CONSTRAINT "FKQBNKCA8RYIKP3TO8BYVL3VJLW" FOREIGN KEY ("IMPORT_ID")
	  REFERENCES "BUDGETEER"."IMPORT" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."PLAN_RECORD" ADD CONSTRAINT "FKQKIRGKL4H9T4JUT7C5THDDS7Y" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "BUDGETEER"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_CONTRACT_FIELD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PROJECT_CONTRACT_FIELD" ADD CONSTRAINT "FKQS6RLK280LCL8K5N8JYQ72AF0" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_USER
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."PROJECT_USER" ADD CONSTRAINT "FK33BXU27D8C3NRV4JAW6D95PM2" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUDGETEER"."BUDGETEER_USER" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."PROJECT_USER" ADD CONSTRAINT "FK4UG72LLNM0N7YAFWNTGDSWL3Y" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "BUDGETEER"."PROJECT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VERIFICATION_TOKEN
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."VERIFICATION_TOKEN" ADD CONSTRAINT "FK9WHWFOEBRH5KXEP2UBKWEY8GJ" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUDGETEER"."BUDGETEER_USER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_RECORD
--------------------------------------------------------

  ALTER TABLE "BUDGETEER"."WORK_RECORD" ADD CONSTRAINT "FK7CYEFPTM8GUFJRT3AHFWCBTEK" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "BUDGETEER"."PERSON" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."WORK_RECORD" ADD CONSTRAINT "FK8VO15TBLPOTTMBL1QR9FD56MJ" FOREIGN KEY ("BUDGET_ID")
	  REFERENCES "BUDGETEER"."BUDGET" ("ID") ENABLE;
  ALTER TABLE "BUDGETEER"."WORK_RECORD" ADD CONSTRAINT "FKNM5IDXHB8GO4DEGKJRV27PN82" FOREIGN KEY ("IMPORT_ID")
	  REFERENCES "BUDGETEER"."IMPORT" ("ID") ENABLE;
