--MUST BE RUN AGAINST THE BRANCH 'RELEASE' COMMIT #73c7cc5 on ORACLE DB

ALTER TABLE BUDGETEER_USER
    ADD(GLOBAL_ROLE NUMBER(10,0) NOT NULL ENABLE,
        ROLES RAW(1024));

CREATE TABLE CONTRACT_SORTING(
    ID NUMBER(19,0) NOT NULL ENABLE,
	SORTING_INDEX NUMBER(10,0),
	CONTRACT_ID NUMBER(19,0) NOT NULL ENABLE,
	USER_ID NUMBER(19,0) NOT NULL ENABLE,
	PRIMARY KEY (ID)
	);

CREATE SEQUENCE SEQ_CONTRACT_SORTING_ID
 START WITH     1
 INCREMENT BY   1
 NOCYCLE;