budgeteer:
  cors:
    allowed-headers:
      - 'Content-Type'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
  jwt:
    issuer: budgeteer
    secret: budgeteer
    max-age: 3600