budgeteer:
  cors:
    allowed-headers:
      - 'Content-Type'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
spring:
  profiles:
    active:
      - dev
      - local
