budgeteer:
  cors:
    allowed-headers:
      - 'Content-Type'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
  mail:
    activate: false
spring:
  profiles:
    active:
      - dev
      - local
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
