name: Build and publish to DockerHub

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA of the commit that should be build and published'
        required: true
        type: string
      repository:
        description: 'Repository that hosts the project that should be build and published'
        required: true
        type: string
      tags:
        description: 'The tags that should be used then publishing the docker image'
        type: string
        required: true
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.tags }}
