name: Build and test and analyze project

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with gradle
        run: ./gradlew build -x spotlessCheck -DmainBranch=$MAIN_BRANCH --no-daemon

      - name: Analyze with SonarQube
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -x spotlessCheck -DmainBranch=$MAIN_BRANCH --no-daemon

      - name: Check codestyle
        if: github.event_name == 'pull_request'
        run: ./gradlew spotlessCheck -DmainBranch=$MAIN_BRANCH --no-daemon

    env:
      MAIN_BRANCH: "${{ github.event.pull_request.base.ref && format('{0}/{1}', 'origin', github.event.pull_request.base.ref) || ''}}"
